#!/usr/bin/env bash

# copyright 2023.
#
# licensed under the apache license, version 2.0 (the "license");
# you may not use this file except in compliance with the license.
# you may obtain a copy of the license at
#
#     http://www.apache.org/licenses/license-2.0
#
# unless required by applicable law or agreed to in writing, software
# distributed under the license is distributed on an "as is" basis,
# without warranties or conditions of any kind, either express or implied.
# see the license for the specific language governing permissions and
# limitations under the license.
#

set -eu -o pipefail

export LOGFILE_NAME="gather-debug.log"

declare OPERATOR_NS=${OPERATOR_NS:-""}
declare OPERATOR=${OPERATOR:-""}
declare KEPLER_NS=${KEPLER_NS:-""}
declare COLLECTION_DIR=${COLLECTION_DIR:-"/must-gather"}
declare SHOW_HELP=false

init_olm() {
	:
}

init_kepler() {
	:
}

init_globals() {
	[[ "$OPERATOR_NS" != "" ]] && init_olm
	[[ "$KEPLER_NS" != "" ]] && init_kepler
	return 0
}

parse_args() {
	while [[ -n "${1+xxx}" ]]; do
		case $1 in
		-h | --help)
			SHOW_HELP=true
			return 0
			;;
		-n | --ns)
			shift
			OPERATOR_NS="$1"
			shift
			;;
		-o | --operator)
			shift
			OPERATOR="$1"
			shift
			;;
		-d | --dest-dir)
			shift
			COLLECTION_DIR="$1"
			shift
			;;
		*)
			return 1
			;;
		esac
	done
	return 0
}

get_timestamp() {
	date -u +"%Y-%m-%d %H:%M:%SZ"
}

log_stdout() {
	echo "$(get_timestamp) $*"
}

log_file() {
	echo "$(get_timestamp) $*" >>"$LOGFILE_PATH"
}

log_stdout_and_file() {
	echo "$(get_timestamp) $*" | tee -a "$LOGFILE_PATH"
}

log() {
	log_stdout_and_file "$@"
}

run() {
	length=$(($# - 1))
	cmd=${*:1:$length}
	gather_file="${*: -1}"

	log_file "$cmd"
	$cmd >>"$gather_file" 2>>"$LOGFILE_PATH" || true
}
