name: Build and Publish Images
description: 'Publishes operator and bundle images to an Image Registry'
outputs:
  version:
    description: "operator version"
    value: ${{ steps.version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Generate Version
      id: version
      shell: bash
      run: |
        version="$(cat VERSION)-$(date +%y%m%d%H%M%S)"
        echo VERSION=$version
        echo "version=$version" >> $GITHUB_OUTPUT
