{
 "title": "Power Monitoring / Namespace",
 "description": "Power-X Monitoring / Namespace",
 "tags": [ "kepler-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kepler_container_package_joules_total, container_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kepler_container_package_joules_total{container_namespace=~\"$namespace\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Consumption (W) in Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum(kepler:container_package_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "PKG"
    },
    {
     "expr": "sum(kepler:container_dram_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "DRAM"
    },
    {
     "expr": "sum(kepler:container_other_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "OTHER"
    },
    {
     "expr": "sum(kepler:container_gpu_watts:1m:by_ns_pod{container_namespace=~\"$namespace\"})",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Total Energy Consumption in Namespace (kWh) - Last 1 hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "kWh" }
   ],
   "targets": [
    {
     "expr": "kepler:container_package_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * 0.000000277777777777778",
     "legendFormat": "PKG (CORE + UNCORE)"
    },
    {
     "expr": "kepler:container_dram_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * 0.000000277777777777778",
     "legendFormat": "DRAM"
    },
    {
     "expr": "kepler:container_other_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * 0.000000277777777777778",
     "legendFormat": "OTHER"
    },
    {
     "expr": "kepler:container_gpu_joules_total:consumed:1h:by_ns{container_namespace=~\"$namespace\"} * 0.000000277777777777778",
     "legendFormat": " GPU"
    }
   ]
  },
  {
   "title": "PKG Power Consumption (W) by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler:container_package_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "DRAM Power Consumption (W) by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "kepler:container_dram_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "GPU Power Consumption (W) by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "W" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (kepler:container_gpu_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "OTHER Power Consumption (W) by Pods",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (kepler:other_joules_watts:1m:by_ns_pod{container_namespace=~\"$namespace\", pod_name=~\"$pod\"})",
     "legendFormat": "{{pod_name}} }}"
    }
   ]
  }
 ]
}