{
 "title": "Power Monitoring /  Overview",
 "description": "PowerX Monitoring overview",
 "tags": [ "kepler-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Architecture by Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (cpu_architecture)(kepler_node_info) "
    }
   ]
  },
  {
   "title": "Total Energy Consumption (kWh) - Last 24 hours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kepler:container_joules_total:consumed:24h:all * 0.000000277777777777778"
    }
   ]
  },
  {
   "title": "Top 10 Energy Consuming Namespaces (kWh) in Last 24 hours",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "topk(10, kepler:container_joules_total:consumed:24h:by_ns) * 0.000000277777777777778",
     "legendFormat": "{{container_namespace}}"
    }
   ]
  }
 ]
}